### ISSUE TITLE
Train and test on standart Human3.6M dataset

### ISSUE THREAD

**Issue by mkocabas** [JimmySuen/integral-human-pose#5]
Hi @JimmySuen,

Great work, thanks for sharing! I wonder how can we modify the images of standart Human3.6M dataset (not the challenge one) to train with your model? I've the videos and images of the original dataset, but I couldn't find a script to modify image paths according to your dataset caches.

**Comment by lck1201** [comment]
Since you have original dataset, you can generate your own cache file by setting different sampling strategy. See _sample_dataset in hm36.py, it provides several sampling method.

**Comment by mkocabas** [comment]
Thanks for the answer @lck1201, by the time I already implemented it. I can get similar reconstruction error now.

**Comment by XiumeiChen** [comment]
@mkocabas Hi, could you share the original H3.6M datasets with me? I've registered on the official net for a few months, but I still don't get the permission. Thank you very much!

**Comment by bucktoothsir** [comment]
@mkocabas Hi 
I am trying to reproduce the paper on standard h36m dataset
Could you tell me how do you prepare dataset?
